### ISSUE TITLE
not able to add dynamic steps 

### ISSUE THREAD

**Issue by Josephdias92** [troch/angular-multi-step-form#17]
im not able to add dynamic steps to the steps array

**Comment by troch** [comment]
This is not a feature available. Once the directive runs, it uses the provided list of steps to create its own internal list of steps. And it is not watching your original list of steps for changes.

**Comment by Josephdias92** [comment]
is there a way to make it work ?

**Comment by troch** [comment]
So one of the reason I don't explicitly support adding and removing steps is because of adding steps before the current one (it would mess up the current index). So what you can do:
- Define which steps are "visible" or "enabled" (using `data` attribute on each step (if data is an object, both your step configuration array and the directive will use the same reference)
- Control the flow using `goToStep(step)` or monkey path `nextStep()` to do what you want it to do (go to the visible / enabled step)
